//bluetooth
const SET_INFODATA = "SET_INFODATA";
const SET_CONNECTBLEDATA = "SET_CONNECTBLEDATA";
const SET_CONNECTPRINTBLE = "SET_CONNECTPRINTBLE";
//equipment
const CHANGE_IPHONE_DATA = "CHANGE_IPHONE_DATA";

//user  
const SET_TOKEN = "SET_TOKEN";
const SET_USERINFO = "SET_USERINFO"
const SET_CLEAR_STATE  = "SET_CLEAR_STATE";

// ble
const SET_BLE_DATA = "SET_BLE_DATA";
const SET_BLE_DATA_PRINT = "SET_BLE_DATA_PRINT";
const SET_CONNECT_DEVICEId = "SET_CONNECT_DEVICEId";
const SET_BLE_DATA_PRINT_LIST = "SET_BLE_DATA_PRINT_LIST";

export {
	SET_INFODATA,
	SET_CONNECTBLEDATA,
	SET_CONNECTPRINTBLE,
	SET_TOKEN,
	SET_USERINFO,
	SET_CLEAR_STATE,
	CHANGE_IPHONE_DATA,
	SET_BLE_DATA,
	SET_BLE_DATA_PRINT,
	SET_CONNECT_DEVICEId,
	SET_BLE_DATA_PRINT_LIST
}