// equipment
const GET_IPHONE_DATA = "GET_IPHONE_DATA";

//user
const GET_TOKEN = "GET_TOKEN";
const GET_USERINFO = "GET_USERINFO";

// ble
const GET_BLE_DATA = "GET_BLE_DATA";
const GET_BLE_DATA_PRINT = "GET_BLE_DATA_PRINT";
const GET_CONNECT_DEVICEId = "GET_CONNECT_DEVICEId";
const GET_BLE_DATA_PRINT_LIST = "GET_BLE_DATA_PRINT_LIST";
export{
	GET_IPHONE_DATA,
	GET_TOKEN,
	GET_USERINFO,
	GET_BLE_DATA,
	GET_BLE_DATA_PRINT,
	GET_CONNECT_DEVICEId,
	GET_BLE_DATA_PRINT_LIST
}